### ISSUE TITLE
rustfmt

### ISSUE THREAD

**Issue by noonien** [najamelan/async_io_stream#1]
Please consider running rustfmt on the source files, so that the formatting style is more idiomatic.

**Comment by najamelan** [comment]
Hi, this issue has come up before and I gave an answer to it [here](https://github.com/thespis-rs/thespis/issues/1). Please read that before continuing.

As something I discovered afterwards, a lot of editors and websites compensate the lack of whitespace by setting line height to 1.5. Because my code uses generous white space already, that really makes it look over the top. Just setting line height to 1.2 will make it look a lot less weird.

Also contributors are not expected to follow my formatting style, I realize I should make the wording in `CONTRIBUTING.md` a bit more explicit.

**Comment by noonien** [comment]
Ah, I was not aware of that issue.

The problem for me was not the whitespace, but the fact that, this style is harder to read, especially after getting used to reading one style of rust code everywhere else.

Thanks.
